logging:
  enabled: true  # Czy logowanie jest włączone

  format:
    timestamp_format: "yyyy-MM-dd HH:mm:ss"  # Format znacznika czasu
    join_format: "[{time}] Player joined: {player}"
    quit_format: "[{time}] Player left: {player}"
    chat_format: "[{time}] Chat - {player}: {message}"
    command_format: "[{time}] Command - {player}: {command}"
    teleport_format: "[{time}] Teleport - {player} to {location}"  # Nowy format logowania teleportacji
    advancement_format: "[{time}] Advancement - {player}: {advancement}"  # Nowy format logowania osiągnięcia
    block_break_format: "[{time}] Block Break - {player}: {block}"  # Nowy format logowania niszczenia bloków

  events:
    log_join: true    # Loguj dołączenia graczy
    log_quit: true    # Loguj wyjścia graczy
    log_chat: true    # Loguj wiadomości na czacie
    log_commands: true  # Loguj użycie komend
    log_teleport: true  # Loguj teleportacje graczy
    log_advancement: true  # Loguj zdobycie osiągnięcia przez graczy
    log_block_break: true  # Loguj niszczenie bloków przez graczy
