name: HTGLoggers
version: '${project.version}'  # Upewnij się, że 'project.version' jest ustawione w Twoim systemie budowy
main: pl.htgmc.htgloggers.HTGLoggers
api-version: '1.20'  # Używamy 1.20 jako minimalnej wersji API
author: 'ToJaWGYT'
description: 'Advanced logging plugin for tracking player activities in Minecraft servers.'
website: 'https://www.spigotmc.org/resources/htgloggers-beta-public-api-beta.119346/'

commands:
  logs:
    description: 'Your command description'  # Opis dla komendy 'logs'

# Zależności (jeśli Twój plugin wymaga innych pluginów)
depend: [PlaceholderAPI]  # Wymagane pluginy, jeśli jakieś są

# Miękkie zależności (plugin będzie działał bez nich, ale z dodatkowymi funkcjonalnościami, jeśli są obecne)
softdepend: []  # Opcjonalne pluginy, które mogą zwiększyć funkcjonalność

# Dodatkowe informacje
load: STARTUP  # Plugin załadowany przy starcie serwera
